### PR TITLE
Fixed DeclareAsNullableCodeFixProvider for casts in variable declarations

### LINKED ISSUE #1392: Declare as nullable code fix for CS8600 breaks when casts are involved
**Product and Version Used**: 

**Steps to Reproduce**:

The following code reports CS8600 because we cast a nullable type to a non-nullable type as part of a variable declaration.
```
    private object? Get() => null;

    internal void Test() {
      var s = (string) Get(); // (1)
      string s2 = (string) Get(); // (2)
    }
```

Roslynator's code fix for CS8600 erroneously assumes the declaration type to be the problem, when it's actually the cast. So we don't get rid of the warning and in case of `var` actually introduce broken code.

**Actual Behavior**:
```csharp
      var? s = (string) Get(); // (1)
      string? s2 = (string) Get(); // (2)
```

**Expected Behavior**:
```csharp
      var s = (string?) Get(); // (1)
      string? s2 = (string?) Get(); // (2)
```

(Although in case of (2) the declaration could be adjusted by another code fix for the same diagnostic, so at least iteratively applying fixes will arrive at the same result.)

### PR DESCRIPTION
**Pull request by jroessel**
Casting a nullable type to a non-nullable type within a variable declaration no longer ignores the cast type and also no longer changes `var` to `var?`.

Fixes #1392.

The code got a little convoluted and the necessity to change two types at the same time required a separate method. I'm still not sure whether there's a good way of queuing two different fixes at the same time, as you can't find your syntax nodes anymore. I hope it's okay enough, though.

### CODE REVIEW

**Comment by jroessel** [comment]
@dotnet-policy-service agree company="yWorks GmbH"

File: src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs [hunk 1]
```diff
@@ -85,4 +90,42 @@ private static void TryRegisterCodeFix(CodeFixContext context, Diagnostic diagno
...
+            {
+                NullableTypeSyntax newType = SyntaxFactory.NullableType(type.WithoutTrivia()).WithTriviaFrom(type);
+                Document changedDocument = await context.Document.ReplaceNodeAsync(type, newType, ct).ConfigureAwait(false);
+
+                // This could be in a variable declaration, so grab the new syntax root and find the newly-replaced type node
+                SyntaxNode root = await changedDocument.GetSyntaxRootAsync(ct).ConfigureAwait(false);
+                SyntaxNode insertedNewType = root.FindNode(type.Span);
+
+                // Try finding a surrounding variable declaration whose type we also have to change
+                if (insertedNewType.AncestorsAndSelf().FirstOrDefault(a => a.IsKind(SyntaxKind.EqualsValueClause)) is EqualsValueClauseSyntax equalsValueClause)
```
Comment (josefpihrt) [inline src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs:111]: I'm not sure about using `AncestorsAndSelf`. I would just check if parent of cast expression is assigned value (`Initializer.Value`).

File: src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs [hunk 2]
```diff
@@ -85,4 +90,42 @@ private static void TryRegisterCodeFix(CodeFixContext context, Diagnostic diagno
...
+                    ExpressionSyntax expression = equalsValueClause.Value;
+
+                    if (equalsValueClause.IsParentKind(SyntaxKind.VariableDeclarator)
+                        && equalsValueClause.Parent.Parent is VariableDeclarationSyntax variableDeclaration
+                        && variableDeclaration.Variables.Count == 1
+                        && !variableDeclaration.Type.IsKind(SyntaxKind.NullableType)
+                        && variableDeclaration.Type is not IdentifierNameSyntax { Identifier.Text: "var" })
+                    {
+                        NullableTypeSyntax newDeclarationType = SyntaxFactory.NullableType(variableDeclaration.Type.WithoutTrivia()).WithTriviaFrom(variableDeclaration.Type);
+                        changedDocument = await changedDocument.ReplaceNodeAsync(variableDeclaration.Type, newDeclarationType, ct).ConfigureAwait(false);
```
Comment (josefpihrt) [inline src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs:122]: Instead of updating document twice, I would rather use something similar like:

```cs
VariableDeclarationSyntax newVariableDeclaration = variableDeclaration
    .ReplaceNode(type, newType)
    .WithType(newDeclarationType);
```

**Review by josefpihrt — CHANGES_REQUESTED** [review]
Please update changelog.

File: src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs (hunk 1 above)
Comment (jroessel) [reply src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs:111]: The thought was to automatically handle perhaps a ParenthesizedExpression around, but yeah, it's probably rare enough to have those in spades around initializers. Especially with the added risk of ancestor-ing through unexpected intermediary expressions. Will change.

File: src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs (hunk 2 above)
Comment (jroessel) [reply src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs:122]: That's ... indeed much simpler. The solution with finding the correct place in the changed document _did_ feel weird and I felt there had to be a better solution. Although it only works in this case because the syntax nodes are practically neighbors, I guess. If the code fix would have to change, say, a field declaration somewhere else, there'd be no way around this dance, right?

File: src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs [hunk 3]
```diff
@@ -85,4 +90,45 @@ private static void TryRegisterCodeFix(CodeFixContext context, Diagnostic diagno
...
+                            } variableDeclaration
+                        }
+                    }
+                    && !declarationType.IsKind(SyntaxKind.NullableType))
+                {
+                    NullableTypeSyntax newDeclarationType = SyntaxFactory.NullableType(declarationType.WithoutTrivia()).WithTriviaFrom(declarationType);
+                    VariableDeclarationSyntax newVariableDeclaration = variableDeclaration
+                        .ReplaceNode(type, newType)
+                        .WithType(newDeclarationType);
+                    return await context.Document.ReplaceNodeAsync(variableDeclaration, newVariableDeclaration, ct).ConfigureAwait(false);
```
Comment (josefpihrt) [inline src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs:123]:
```suggestion
                        .WithType(newDeclarationType);

                    return await context.Document.ReplaceNodeAsync(variableDeclaration, newVariableDeclaration, ct).ConfigureAwait(false);
```

File: src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs (hunk 2 above)
Comment (josefpihrt) [reply src/CodeFixes/CSharp/CodeFixes/DeclareAsNullableCodeFixProvider.cs]: Updating multiple nodes can be tricky. And there many approaches. You can use SyntaxRewriter, method SyntaxNode.ReplaceNodes, SyntaxAnnotation to find a node in a new tree. If you are replacing members or statements you can use its index to find it in a collection etc.

File: ChangeLog.md [hunk 4]
```diff
@@ -19,6 +19,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 - Fix analyzer [RCS0049](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS0049) ([PR](https://github.com/dotnet/roslynator/pull/1386))
 - Fix analyzer [RCS1159](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1159) ([PR](https://github.com/dotnet/roslynator/pull/1390))
+- Fix code fix for [CS8600](https://josefpihrt.github.io/docs/roslynator/fixes/CS8600) changing the wrong type when casts or `var` are involved ([PR](https://github.com/dotnet/roslynator/pull/1393))
```
Comment (josefpihrt) [inline ChangeLog.md:22]:
```suggestion
- Fix code fix for [CS8600](https://josefpihrt.github.io/docs/roslynator/fixes/CS8600) changing the wrong type when casts or `var` are involved ([PR](https://github.com/dotnet/roslynator/pull/1393))
```
```suggestion
- Fix code fix for [CS8600](https://josefpihrt.github.io/docs/roslynator/fixes/CS8600) changing the wrong type when casts or `var` are involved ([PR](https://github.com/dotnet/roslynator/pull/1393) by @jroessel)
```

**Review by josefpihrt — APPROVED** [review]

**Comment by josefpihrt** [comment]
Thank you for the contribution @jroessel !
