### PR TITLE
Fix RCS1234

### LINKED ISSUE #1123: RCS1234 false positive
**Product and Version Used**: 4.3.0

**Steps to Reproduce**:

```csharp
public enum Foo
{
    [Obsolete]
    Bar = 1,

    Baz = 1, // RCS1234
}
```

If `Bar` is obsolete it should not be used as a replacement for 1 because that would produce compiler warning.

### PR DESCRIPTION
**Pull request by jakubreznak**
fixes #1123

### CODE REVIEW

**Comment by jakubreznak** [comment]
@dotnet-policy-service agree

File: src/CSharp/CSharp/CSharpUtility.cs [hunk 1]
```diff
@@ -681,4 +681,11 @@ public static SeparatedSyntaxList<TypeParameterSyntax> GetTypeParameters(SyntaxN
                 return null;
         }
     }
+
+    public static bool IsEnumMemberObsolete(EnumMemberDeclarationSyntax enumMember)
+    {
+        return enumMember.AttributeLists
+            .SelectMany(attrList => attrList.Attributes)
+            .Any(attribute => attribute.Name.ToString() == "Obsolete");
+    }
```
Comment (josefpihrt) [inline src/CSharp/CSharp/CSharpUtility.cs:690]: This implementation probably would work for most of cases but I believe it could be improved.

It's better to use a symbol and check if it has an attribute. The symbol variable is already present in the analyzer and also in the code fix provider so this should be easy.

The method to be used is `symbol.HasAttribute(MetadataName)` and static class `MetadataNames` already contains member `MetadataNames.System_ObsoleteAttribute`.

As a result the method will be more general as it will check if a symbol is marked with `Obsolete` attribute.

**Review by josefpihrt — CHANGES_REQUESTED** [review]

File: src/CSharp/CSharp/CSharpUtility.cs (hunk 1 above)
Comment (jakubreznak) [reply src/CSharp/CSharp/CSharpUtility.cs]: Thanks for the suggestion. I've updated the code to use `symbol.HasAttribute(MetadataNames.System_ObsoleteAttribute)` as recommended. I really appreciate your feedback.

**Review by josefpihrt — APPROVED** [review]

**Comment by josefpihrt** [comment]
Thanks for the contribution!
